//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRVacationSystemDL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRVacationEntities : DbContext
    {
        public HRVacationEntities()
            : base("name=HRVacationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<PersonelRole> PersonelRole { get; set; }
        public virtual DbSet<PersonelVacation> PersonelVacation { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<VacationType> VacationType { get; set; }
    }
}
