//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRVacationSystemDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelVacation
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int PersonelId { get; set; }
        public int VacationTypeId { get; set; }
        public Nullable<System.DateTime> VacationStartDate { get; set; }
        public Nullable<System.DateTime> VacationEndDate { get; set; }
        public bool IsDone { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual VacationType VacationType { get; set; }
        public virtual VacationType VacationType1 { get; set; }
    }
}
