//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRVacationSystemDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelRole
    {
        public int PersonelId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> RelatedSeniorId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual Role Role { get; set; }
    }
}
